// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Todo.Api.DbContexts;

namespace TodoApi.Migrations
{
    [DbContext(typeof(TodoContext))]
    partial class TodoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TodoApi.Entities.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("36a12bfa-d2c4-4dc9-9906-eae63b4319a0"),
                            AssignTo = "a1@gmail.com",
                            City = "city1",
                            DueDate = new DateTime(2021, 7, 28, 0, 38, 48, 55, DateTimeKind.Local).AddTicks(5786),
                            Name = "Todo 1",
                            Priority = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("36a12bfa-1111-2222-3333-eae63b4319a0"),
                            AssignTo = "a2@gmail.com",
                            City = "city2",
                            DueDate = new DateTime(2021, 7, 28, 0, 38, 48, 57, DateTimeKind.Local).AddTicks(4992),
                            Name = "Todo 2",
                            Priority = 0,
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
